import type { PlatformDesignTokens, ThemeMode } from "./types";

export const defaultTokens: Record<ThemeMode, PlatformDesignTokens> = {
  dark: {
    mode: "dark",
    colors: {
      background: "#0f172a",
      surface: "#1e293b",
      surfaceBorder: "#334155",
      primary: "#6366f1",
      primaryForeground: "#ffffff",
      textPrimary: "#f8fafc",
      textSecondary: "#cbd5e1",
      textMuted: "#64748b",
      accent: "#38bdf8",
      success: "#34d399",
      warning: "#fbbf24",
      danger: "#f87171",
      info: "#818cf8",
    },
    typography: {
      fontFamilySans: "Inter, system-ui, sans-serif",
      fontFamilyMono: "JetBrains Mono, monospace",
      fontSizeXs: "0.75rem",
      fontSizeSm: "0.875rem",
      fontSizeBase: "1rem",
      fontSizeLg: "1.125rem",
      fontSizeXl: "1.25rem",
    },
    spacing: {
      xs: "0.25rem",
      sm: "0.5rem",
      md: "1rem",
      lg: "1.5rem",
      xl: "2rem",
      containerPadding: "1rem",
      gridGap: "0.5rem",
    },
    borderRadius: "0.5rem",
    shadow: "0 4px 6px -1px rgba(0, 0, 0, 0.3)",
  },
  light: {
    mode: "light",
    colors: {
      background: "#f8fafc",
      surface: "#ffffff",
      surfaceBorder: "#e2e8f0",
      primary: "#4f46e5",
      primaryForeground: "#ffffff",
      textPrimary: "#0f172a",
      textSecondary: "#475569",
      textMuted: "#94a3b8",
      accent: "#0284c7",
      success: "#059669",
      warning: "#d97706",
      danger: "#dc2626",
      info: "#4f46e5",
    },
    typography: {
      fontFamilySans: "Inter, system-ui, sans-serif",
      fontFamilyMono: "JetBrains Mono, monospace",
      fontSizeXs: "0.75rem",
      fontSizeSm: "0.875rem",
      fontSizeBase: "1rem",
      fontSizeLg: "1.125rem",
      fontSizeXl: "1.25rem",
    },
    spacing: {
      xs: "0.25rem",
      sm: "0.5rem",
      md: "1rem",
      lg: "1.5rem",
      xl: "2rem",
      containerPadding: "1rem",
      gridGap: "0.5rem",
    },
    borderRadius: "0.5rem",
    shadow: "0 1px 3px 0 rgba(0, 0, 0, 0.1)",
  },
  "high-contrast": {
    mode: "high-contrast",
    colors: {
      background: "#000000",
      surface: "#111111",
      surfaceBorder: "#ffffff",
      primary: "#ffff00",
      primaryForeground: "#000000",
      textPrimary: "#ffffff",
      textSecondary: "#e0e0e0",
      textMuted: "#aaaaaa",
      accent: "#00ffff",
      success: "#00ff00",
      warning: "#ffaa00",
      danger: "#ff0000",
      info: "#00ffff",
    },
    typography: {
      fontFamilySans: "system-ui, sans-serif",
      fontFamilyMono: "monospace",
      fontSizeXs: "0.8rem",
      fontSizeSm: "0.95rem",
      fontSizeBase: "1.1rem",
      fontSizeLg: "1.25rem",
      fontSizeXl: "1.5rem",
    },
    spacing: {
      xs: "0.25rem",
      sm: "0.5rem",
      md: "1rem",
      lg: "1.5rem",
      xl: "2rem",
      containerPadding: "1rem",
      gridGap: "0.75rem",
    },
    borderRadius: "0rem",
    shadow: "none",
  },
  cyberpunk: {
    mode: "cyberpunk",
    colors: {
      background: "#0d0221",
      surface: "#0f0826",
      surfaceBorder: "#ff007f",
      primary: "#ff007f",
      primaryForeground: "#ffffff",
      textPrimary: "#00f6ff",
      textSecondary: "#d600ff",
      textMuted: "#682d8c",
      accent: "#fefe00",
      success: "#00ff66",
      warning: "#ffaa00",
      danger: "#ff0055",
      info: "#00f6ff",
    },
    typography: {
      fontFamilySans: "system-ui, sans-serif",
      fontFamilyMono: "monospace",
      fontSizeXs: "0.75rem",
      fontSizeSm: "0.875rem",
      fontSizeBase: "1rem",
      fontSizeLg: "1.125rem",
      fontSizeXl: "1.25rem",
    },
    spacing: {
      xs: "0.25rem",
      sm: "0.5rem",
      md: "1rem",
      lg: "1.5rem",
      xl: "2rem",
      containerPadding: "1rem",
      gridGap: "0.5rem",
    },
    borderRadius: "0.25rem",
    shadow: "0 0 10px rgba(255, 0, 127, 0.4)",
  },
  emerald: {
    mode: "emerald",
    colors: {
      background: "#022c22",
      surface: "#064e3b",
      surfaceBorder: "#047857",
      primary: "#10b981",
      primaryForeground: "#ffffff",
      textPrimary: "#ecfdf5",
      textSecondary: "#a7f3d0",
      textMuted: "#34d399",
      accent: "#6ee7b7",
      success: "#10b981",
      warning: "#f59e0b",
      danger: "#ef4444",
      info: "#3b82f6",
    },
    typography: {
      fontFamilySans: "Inter, system-ui, sans-serif",
      fontFamilyMono: "JetBrains Mono, monospace",
      fontSizeXs: "0.75rem",
      fontSizeSm: "0.875rem",
      fontSizeBase: "1rem",
      fontSizeLg: "1.125rem",
      fontSizeXl: "1.25rem",
    },
    spacing: {
      xs: "0.25rem",
      sm: "0.5rem",
      md: "1rem",
      lg: "1.5rem",
      xl: "2rem",
      containerPadding: "1rem",
      gridGap: "0.5rem",
    },
    borderRadius: "0.5rem",
    shadow: "0 4px 6px -1px rgba(0, 0, 0, 0.3)",
  },
};
